Thomas/improve persistence performance
diffblue/telescope pull request #70
Opened 2020-12-14 21:29 UTC by ThomasPerkins1123

2020-12-15 10:34 UTC, EnricoTrentin requested changes
As discussed, I've left a few comments with proposed changes to this PR

2020-12-15 10:34 UTC, EnricoTrentin commented on core/src/main/java/com/diffblue/telescope/persistence/ReportDAO.java
> +        EntityManager entityManager = ENTITY_MANAGER_FACTORY.createEntityManager();
The creation of entityManager should be done outside addModuleMetric.
I suggest it's moved in a constructor.

2020-12-15 10:34 UTC, EnricoTrentin commented on core/src/main/java/com/diffblue/telescope/persistence/ReportDAO.java
> +    private static EntityManagerFactory ENTITY_MANAGER_FACTORY = Persistence.createEntityManagerFactory("TelescopeDev");  //TODO: Get this from a maven profile e.t.c
In order to get the connection details from application properties, you can pass a map of properties to createEntityManagerFactory.
A possible implementation would involve having the factory in a constructor that takes the properties as an argument.
I also suggest having a constructor that does not take properties as an argument and uses default values instead.

2020-12-15 10:34 UTC, EnricoTrentin commented on model/src/main/java/com/diffblue/telescope/metrics/Metric.java
> +        this.humanReadableValue = value.toString();
If toString() exceeds 2000 characters the entire transaction will fail, this needs to be prevented.
You could decide to change the datatype of the column (for example, TEXT),
or since this field is only used for debugging, you might be fine with truncating strings longer than the max characters

2020-12-15 10:34 UTC, EnricoTrentin commented on model/src/main/java/com/diffblue/telescope/metrics/Metric.java
>      @Column(name = "value", nullable = false, columnDefinition = "varchar(2000)")
Does the serialisation always produce a string shorter than 2000 characters?
We might be fine with the loss of data in the humanReadableValue field, but not this one

2020-12-15 10:34 UTC, EnricoTrentin commented on model/src/main/java/com/diffblue/telescope/metrics/ModuleMetrics.java
> +        this.reportType = "hybrid";
Are you planning to use this?

2020-12-15 15:49 UTC, ThomasPerkins1123 commented on model/src/main/java/com/diffblue/telescope/metrics/Metric.java
>      @Column(name = "value", nullable = false, columnDefinition = "varchar(2000)")
Short answer is no, the longest I have seen so far is 780 but it might be possible if we saw every single dcover error to go over but if we are going to redo this field with the json stuff I think this is fine

2020-12-15 15:50 UTC, ThomasPerkins1123 commented on model/src/main/java/com/diffblue/telescope/metrics/ModuleMetrics.java
> +        this.reportType = "hybrid";
No, I can remove it but I just wanted to see this if I ever accidentally saved one of these

2020-12-16 10:32 UTC, EnricoTrentin approved these changes

2020-12-16 11:51 UTC, merged